### ISSUE TITLE
sanitize, sanitaization の邦訳

### ISSUE THREAD

**Issue by coky-t** [owasp-ja/asvs-ja#55]
0x13-V5-Validation-Sanitization-Encoding.md には sanitize, sanitaization の邦訳として「サニタイズ」「無害化」の2種類が存在しています。いずれかに統一したほうがよいと思います。

**Comment by okdt** [comment]
サニタイズ、にしませんか。日に当てることを言ってるわけで、無害になるのはその結果であって。なんかピンと来てないんです。バリデーションがカタカナ行きなら、サニタイズもそれでいいと思います。どうでしょう。
