### ISSUE TITLE
章タイトル内の and の邦訳

### ISSUE THREAD

**Issue by coky-t** [owasp-ja/asvs-ja#56]
章タイトルには and を含むものがありますが、邦訳が統一されていません。

「A, B and C」
V1: Architecture, Design and Threat Modeling Requirements
V5: Validation, Sanitization and Encoding Verification Requirements
(邦訳)
V1: アーキテクチャ、設計、脅威モデリング要件
V5: バリデーション、無害化とエンコーディングの検証要件

「A and B」
V7: Error Handling and Logging Verification Requirements
V12: File and Resources Verification Requirements
V13: API and Web Service Verification Requirements
(邦訳)
V7: エラー処理およびログ記録の検証要件
V12: ファイルとリソースの検証要件
V13: API、Webサービスの検証要件

**Comment by okdt** [comment]
> V1: アーキテクチャ、設計、脅威モデリング要件
・アーキテクチャ
・設計
・脅威モデリング要件

に見えてしまうので、これら３項目の要件だということがわかるようにしたいですね。

・「および」「と」「、」を統一するかどうか
・本来の意味が読者に伝わるどうか
・シンプルか

あたり、考えたいです。

**Comment by okdt** [comment]
「A, B and C」
V1: Architecture, Design and Threat Modeling Requirements
V5: Validation, Sanitization and Encoding Verification Requirements
(邦訳)
V1: アーキテクチャ、設計および脅威モデリングの要件
V5: バリデーション、サニタイゼーションおよびエンコーディングの検証要件

「A and B」
V7: Error Handling and Logging Verification Requirements
V12: File and Resources Verification Requirements
V13: API and Web Service Verification Requirements
(邦訳)
V7: エラー処理とログ記録の検証要件
V12: ファイルとリソースの検証要件
V13: APIとWebサービスの検証要件

こんな感じでどうでしょうか。
