### ISSUE TITLE
Appendix B 「この基準」

### ISSUE THREAD

**Issue by coky-t** [owasp-ja/asvs-ja#57]
0x91-Appendix-B_References.md L.3
「以下の OWASP プロジェクトは、この基準のユーザや採用者に役立つ可能性が高い:」

原文
「The following OWASP projects are most likely to be useful to users/adopters of this standard:」

「this standard」は他の個所では「この標準」としているが、この文でのみ「この基準」としている。

**Comment by okdt** [comment]
以下に示すOWASPプロジェクトはASVSを利活用する方々に役立つことでしょう。

かな。
